language: nodejs
nodejs: 
- 11.11.0
cache: npm

script:
  - npm install
  - npm run gh

deploy: 
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages

# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy: