language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
# language: node_js
# node_js:
#   - "11"
#   - "node"
# env:
#   - WEBPACK_VERSION= # Current, from package.json
#   - WEBPACK_VERSION=4
# install:
#   # Use npm 5.7.x since it has introduced `npm ci`
#   - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
#   - npm ci
# before_script:
#   # Install Webpack version
#   - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi

# script:
#   - npm i
#   - npm run build
#   - git remote add origin https://github.com/shijiezhou1/vue-portfolio.git
#   - npm run gh

# branches:
#   only:
#     - gh-pages

# deploy: 
#   provider: pages
#   skip-cleanup: true
#   local_dir: dist/
#   keep_history: true
#   github-token: $GITHUB_TOKEN
#   on:
#     branch: gh-pages

# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy: