version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - add_ssh_key:
          fingerprints:
            - "38:25:f6:09:9c:05:b5:e1:7b:62:c2:44:c0:cc:0e:a8"
      - checkout
      - attach_workspace:
          at: dist/
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "cs5129606@gmail.com"
            git config user.name "shijiezhou1"
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/setup-github.sh
            fi
