version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: dist/
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - deploy:
          name: Deploy Release to GitHub
          command: ./setup-github.sh
